# Dockerfile
FROM postgres:alpine

# Set DB credentials and default DB
ENV POSTGRES_USER=admin
ENV POSTGRES_PASSWORD=mypassword
ENV POSTGRES_DB=mydb

COPY init.sql /docker-entrypoint-initdb.d/

# Optional: seed SQL
# COPY init.sql /docker-entrypoint-initdb.d/

EXPOSE 5432